-- MySQL Script generated by MySQL Workbench
-- Sun Dec  6 12:36:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bolnica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bolnica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bolnica` DEFAULT CHARACTER SET utf8 ;
USE `bolnica` ;

-- -----------------------------------------------------
-- Table `bolnica`.`bolnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`bolnica` (
  `bolnica_id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `lokacija` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bolnica_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`odjel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`odjel` (
  `odjel_id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `sprat_na_kojem_se_nalazi` INT NOT NULL,
  PRIMARY KEY (`odjel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`radnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`radnik` (
  `radnik_id` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `datum_rodjenja` DATE NOT NULL,
  `adresa_stanovanja` VARCHAR(45) NOT NULL,
  `bolnica_id` INT NOT NULL,
  `odjel_id` INT NOT NULL,
  PRIMARY KEY (`radnik_id`),
  CONSTRAINT `fk_bolnica_id`
    FOREIGN KEY (`bolnica_id`)
    REFERENCES `bolnica`.`bolnica` (`bolnica_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_odjel_id`
    FOREIGN KEY (`odjel_id`)
    REFERENCES `bolnica`.`odjel` (`odjel_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`doktor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`doktor` (
  `doktor_id` INT NOT NULL,
  `specijalizacija` VARCHAR(45) NOT NULL,
  `dezura` INT NOT NULL,
  `radnik_id` INT NOT NULL,
  PRIMARY KEY (`doktor_id`),
  CONSTRAINT `fk_radnik_id`
    FOREIGN KEY (`radnik_id`)
    REFERENCES `bolnica`.`radnik` (`radnik_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`pacijent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`pacijent` (
  `pacijent_id` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `bolnica_id` INT NOT NULL,
  PRIMARY KEY (`pacijent_id`),
  CONSTRAINT `fk_bolnica1_id`
    FOREIGN KEY (`bolnica_id`)
    REFERENCES `bolnica`.`bolnica` (`bolnica_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`posjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`posjeta` (
  `posjeta_id` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `datum_posjete` DATE NOT NULL,
  `pacijent_id` INT NOT NULL,
  PRIMARY KEY (`posjeta_id`),
  CONSTRAINT `fk_pacijent_id`
    FOREIGN KEY (`pacijent_id`)
    REFERENCES `bolnica`.`pacijent` (`pacijent_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`karton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`karton` (
  `karton_id` INT NOT NULL,
  `naziv_bolesti` VARCHAR(45) NULL,
  `datum_pocetka_lijecenja` DATE NULL,
  `datum_primanja_u_bolnicu` DATE NULL,
  `datum_izlaska_iz_bolnice` DATE NULL,
  `pacijent_id` INT NOT NULL,
  PRIMARY KEY (`karton_id`),
  CONSTRAINT `fk_pacijent1_id`
    FOREIGN KEY (`pacijent_id`)
    REFERENCES `bolnica`.`pacijent` (`pacijent_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`lijekovi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`lijekovi` (
  `lijekovi_id` INT NOT NULL,
  `naziv_lijeka` VARCHAR(45) NOT NULL,
  `proizvodjac` VARCHAR(45) NOT NULL,
  `br_dana_koristenja_terapije` INT NULL,
  `karton_id` INT NOT NULL,
  PRIMARY KEY (`lijekovi_id`),
  CONSTRAINT `fk_karton_id`
    FOREIGN KEY (`karton_id`)
    REFERENCES `bolnica`.`karton` (`karton_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`ugovor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`ugovor` (
  `ugovor_id` INT NOT NULL,
  `plata` DOUBLE NOT NULL,
  `datum_zaposlenja` DATE NOT NULL,
  `broj_racuna` VARCHAR(45) NOT NULL,
  `radnik_id` INT NOT NULL,
  PRIMARY KEY (`ugovor_id`),
  CONSTRAINT `fk_radnik1_id`
    FOREIGN KEY (`radnik_id`)
    REFERENCES `bolnica`.`radnik` (`radnik_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`cistacica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`cistacica` (
  `cistacica_id` INT NOT NULL,
  `radnik_id` INT NOT NULL,
  PRIMARY KEY (`cistacica_id`),
  CONSTRAINT `fk_radnik2_id`
    FOREIGN KEY (`radnik_id`)
    REFERENCES `bolnica`.`radnik` (`radnik_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`medtehnicar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`medtehnicar` (
  `medtehnicar_id` INT NOT NULL,
  `dezura` INT NOT NULL,
  `radnik_id` INT NOT NULL,
  PRIMARY KEY (`medtehnicar_id`),
  CONSTRAINT `fk_radnik3_id`
    FOREIGN KEY (`radnik_id`)
    REFERENCES `bolnica`.`radnik` (`radnik_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`pacijent_medtehnicar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`pacijent_medtehnicar` (
  `pacijent_id` INT NOT NULL,
  `medtehnicar_id` INT NOT NULL,
  PRIMARY KEY (`pacijent_id`),
  CONSTRAINT `fk_pacijent2_id`
    FOREIGN KEY (`pacijent_id`)
    REFERENCES `bolnica`.`pacijent` (`pacijent_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medtehnicar_id`
    FOREIGN KEY (`medtehnicar_id`)
    REFERENCES `bolnica`.`medtehnicar` (`medtehnicar_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`vozac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`vozac` (
  `vozac_id` INT NOT NULL,
  `dezura` INT NOT NULL,
  `radnik_id` INT NOT NULL,
  PRIMARY KEY (`vozac_id`),
  CONSTRAINT `fk_radnik4_id`
    FOREIGN KEY (`radnik_id`)
    REFERENCES `bolnica`.`radnik` (`radnik_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`pacijent_doktor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`pacijent_doktor` (
  `pacijent_id` INT NOT NULL,
  `doktor_id` INT NOT NULL,
  PRIMARY KEY (`pacijent_id`),
  CONSTRAINT `fk_pacijent3_id`
    FOREIGN KEY (`pacijent_id`)
    REFERENCES `bolnica`.`pacijent` (`pacijent_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doktor_id`
    FOREIGN KEY (`doktor_id`)
    REFERENCES `bolnica`.`doktor` (`doktor_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolnica`.`hitna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolnica`.`hitna` (
  `hitna_id` INT NOT NULL,
  `vrsta_vozila` VARCHAR(45) NOT NULL,
  `registarske_table` VARCHAR(45) NOT NULL,
  `zauzeto` VARCHAR(45) NOT NULL,
  `doktor_id` INT NOT NULL,
  `medtehnicar_id` INT NOT NULL,
  `vozac_id` INT NOT NULL,
  PRIMARY KEY (`hitna_id`),
  CONSTRAINT `fk_doktor1_id`
    FOREIGN KEY (`doktor_id`)
    REFERENCES `bolnica`.`doktor` (`doktor_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medtehnicar1_id`
    FOREIGN KEY (`medtehnicar_id`)
    REFERENCES `bolnica`.`medtehnicar` (`medtehnicar_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vozac_id`
    FOREIGN KEY (`vozac_id`)
    REFERENCES `bolnica`.`vozac` (`vozac_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
